### ISSUE TITLE
New feature - add Toggl task name to JIRA Work description

### ISSUE THREAD

**Issue by vipetrul** [christianrondeau/jira-toggl-sync#6]
Hello,
I really like your simple console app, it works like a charm - well done.
I would like to improve it by also saving toggl's task name into work log item description.
Once this feature is implemented,  I would like to also implement optional purge feature, that would purge JIRA's work log items that are out of sync with toggl. This would allow to push toggl time entries to JIRA without creating duplicate JIRA work log items.

I wanted to hear your opinion on this before I begin.
Thank you!

**Comment by christianrondeau** [comment]
Hi! Thanks for the compliment, it's always appreciated when what you build is being used :)

I think what you're suggesting makes a lot of sense. Some people actually only use the JIRA number as the Task description, so that would not *always* be useful, might be good to have a `workLogItemDescriptionTemplate="{{toggl:taskDescription}}"` so that we can scale the feature later (e.g. using the machine name on which the task was created, or whatever we may need in the future).

If the template is empty or missing, we would not create a description.

If you think that makes sense, and if you're open to providing a PR, I'll certainly look at it :)

As for the purge feature, that is extremely interesting, and also a little bit frightening ;) I'd like to hear exactly how you would plan to ensure that the right tasks are cleared. You can open another issue for this.

Thanks for participating!

**Comment by vipetrul** [comment]
The main challenge is to uniquely identify JIRA's work log items that originated from toggl. After reviewing JIRA API documentation I don't see any other easy way to do this except for storing this info in work log comment. For example, the comment could look like this:
```
Toggl time entry id: 123123
[TEST-43] Writing tests for feature ABC
```
We can perhaps allow users to customize what is displayed below `Toggl time entry id: #` via templates (as you suggested), but toggl time entry identification line should stay unchanged, because other functionality will depend on it.

**Comment by christianrondeau** [comment]
I like that. So the template could *require* a match with a regex in the work log entry, e.g. `[toggl-id:12345]`. If it doesn't find this, it won't purge it.

And the default template could look like `{{toggl:description}} {{toggl:id}}`.

That would kill two birds with one stone. Poor birds.

**Comment by vipetrul** [comment]
Yeah, something like that could work. Let me fork and make a first iteration, and then we will go from there.

**Comment by christianrondeau** [comment]
Looking forward to it :)

**Comment by christianrondeau** [comment]
It's now included! Thanks for your PR :)
