### ISSUE TITLE
Option to purge JIRA

### ISSUE THREAD

**Issue by vipetrul** [christianrondeau/jira-toggl-sync#8]
I put together specs that describe how JIRA purge functionality may work:
https://docs.google.com/spreadsheets/d/1H5RMyGdTcZENyP-95IalQJfbSDECKIGM9J4x8eN4Sn4/edit?usp=sharing

I think if this is implemented then process can fully mirror Toggl entries with JIRA.
Could you please review to make sure I didn't miss any use-cases.
Thank you.

**Comment by christianrondeau** [comment]
That looks fine. I think because this could have some very frustrating side effects, it would be important to print exactly which time entries will be purged, e.g.:

```
4 JIRA worklogs found in the specified time span referencing a Toggl worklog that we're about to create:
  * XXX-00000: 9:00 - 9:30 description
  * XXX-00000: 9:00 - 9:30 description
  * XXX-00000: 9:00 - 9:30 description
  * XXX-00000: 9:00 - 9:30 description
Not purging these items will result in duplicates.
Delete these JIRA worklogs? [y/n]: y
Purging 5 JIRA worklogs.
3 JIRA worklogs found referencing a Toggl worklog that we don't know about. It might have been deleted.
  * XXX-00000: 9:00 - 9:30 description
  * XXX-00000: 9:00 - 9:30 description
  * XXX-00000: 9:00 - 9:30 description
Delete these JIRA worklogs? [y/n]: y
Purging 3 JIRA worklogs.
```

This is just an example of the output. My goal is to:

1. Avoid loosing all your worklogs due to an error in the code (e.g. in the future) or in the typed timespan
2. Avoid fearing the tool by having control over what it will delete, even with purging enabled.
3. Quickly identify if the suggestions make sense by seeing how many items will be deleted, and which ones (the JIRA number, the time span and the toggl description if we have it)

This way, even if we get the specs wrong, the damage will be controlle.

**Comment by vipetrul** [comment]
To implement purge functionality, we need to be able to call [worklog API](https://docs.atlassian.com/jira/REST/server/#api/2/worklog) directly, specifically:
* Get ids of worklogs modified since
* Get worklogs for ids

[Jira Rest Client](https://github.com/techtalk/JiraRestClient ) we currently using doesn't have those endpoints implemented. Although, there is a [pull request](https://github.com/techtalk/JiraRestClient/pull/36) that implements those endpoints. But unfortunately it doesn't appear that JiraRastClient is being actively maintained.

There is also an alternative: https://bitbucket.org/farmas/atlassian.net-sdk/wiki/Home , but they don't have these endpoints implemented either.

So what would be your recommendation:
* Implement our own?
* Fork implementation from [here](https://github.com/techtalk/JiraRestClient/pull/36) ?
* something else?

Thank you

**Comment by vipetrul** [comment]
Actually, we should be able to find all the worklogs by going through recently updated JIRA issues. Please ignore my comment above.

**Comment by christianrondeau** [comment]
Since I use a submodule rather than a reference to the NuGet package, we could very well use a fork, or fork it ourselves, I see some are actually maintained: https://github.com/techtalk/JiraRestClient/network

Let me know what you need, and I'll fork it. I also see multiple branches out there, https://github.com/Anastasius80/JiraRestClient has some active maintaining too... though as long as the API we actually need are there, we're good. In the end, we could write our own but it's just a wrapper for JSON calls over HTTP.

Another possibility is to switch to another implementation, this one seems maintained: https://bitbucket.org/farmas/atlassian.net-sdk/wiki/Home - but there will be some conversion work (not much, but still).

Let me know if you have a preference; since there is not much of the Atlassian API we actually need, just writing a simple JSON client would probably be fine too. https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis

Let me know if I can help further :)

**Comment by vipetrul** [comment]
I appreciate you looking into this. At this point we've everything we need.
Let me complete my first iteration and then we will refine it further - this is when we might decide to use another JIRA client.
